### ISSUE TITLE
Won't launch - "permission denied"

### ISSUE THREAD

**Issue by kz6fittycent** [Thermionix/fusion360#1]
Firstly, thanks so much for all your hard work creating this snap. However, I can't seem to get it to load. Here's what I'm seeing when attempting to run it via terminal:

```
...
(yad:39531): dbind-WARNING **: 10:26:13.163: Couldn't connect to accessibility bus: Failed to connect to socket /tmp/dbus-ivPyn41GHK: No such file or directory
shm_unlink: No such file or directory
shm_open: Permission denied
ftruncate: Bad file descriptor
esync: up and running.
removed '/tmp/Fusion%20360%20Admin%20Install.exe'
/snap/fusion360/10/bin/sommelier: line 102: 39567 Broken pipe             yes
     39568 Terminated              | yad --progress --title="Installing ${EXE_NAME}" --progress-text= --width=400 --center --no-buttons --auto-close --auto-kill --on-top --pulsate
Running hook '/snap/fusion360/10/sommelier/hooks/post-install'
updated RUN_EXE=
Starting application..
```
Snap info:
```
snap --version
snap    2.51.3
snapd   2.51.3
series  16
pop     21.04
kernel  5.11.0-7620-generic
```

OS info:
```
OS: Pop!_OS 21.04 x86_64 
Kernel: 5.11.0-7620-generic 
```
Fusion360 snap info:
```
snap info fusion360 
name:      fusion360
summary:   Integrated CAD, CAM, CAE, and PCB software.
publisher: Michael Bond (thermionix)
store-url: https://snapcraft.io/fusion360
contact:   https://github.com/Thermionix/fusion360
license:   unset
description: |
  _Developed by Autodesk_
  
  Features
    * Parametric Modelling
    * Program tool paths for CNC machines
    * 3D Rendering
    * Export STL models for the 3D Printer
  
  **known issues:**
  * Floating toolbars
  * Hangs on exit
commands:
  - fusion360
  - fusion360.wine
  - fusion360.winetricks
snap-id:      8qsIvaV1JD8Ne3p3UcS8701cbJmOGqHw
tracking:     latest/stable
refresh-date: today at 09:31 CDT
channels:
  latest/stable:    0.6 2021-08-12 (10) 184kB -
  latest/candidate: ↑                         
  latest/beta:      ↑                         
  latest/edge:      ↑                         
installed:          0.6            (10) 184kB -
```

**Comment by cryinkfly** [comment]
@kz6fittycent Hey, you can use this command before you running this snap app: 

> export NO_AT_BRIDGE=1

Then it's so, the accessibility warning is a known bug.

**Comment by kz6fittycent** [comment]
Hey, I made sure to run the export command, here's what's happening now:

```
shm_unlink: No such file or directory
shm_open: Permission denied
ftruncate: Bad file descriptor
esync: up and running.
removed '/tmp/Fusion%20360%20Admin%20Install.exe'
/snap/fusion360/10/bin/sommelier: line 102: 60291 Broken pipe             yes
     60292 Terminated              | yad --progress --title="Installing ${EXE_NAME}" --progress-text= --width=400 --center --no-buttons --auto-close --auto-kill --on-top --pulsate
Running hook '/snap/fusion360/10/sommelier/hooks/post-install'
updated RUN_EXE=
Starting application..
```

**Comment by cryinkfly** [comment]
@kz6fittycent The Installation via the store works, but nothing happens after downloading the installer!


https://user-images.githubusercontent.com/79079633/129252909-97f83ca7-a119-48ec-b333-d31ecf787dae.mp4

**Comment by Rohan-Bansal** [comment]
This is great work! Same issue however.
```bash
Initialising Wine..
Gtk-Message: 12:24:22.280: Failed to load module "appmenu-gtk-module"
shm_open: Permission denied
ftruncate: Bad file descriptor
esync: up and running.
Installing application..
Running hook '/snap/fusion360/10/sommelier/hooks/pre-install'
Gtk-Message: 12:24:28.984: Failed to load module "appmenu-gtk-module"
grep: /home/kronos/snap/fusion360/common/.wine/*.reg: No such file or directory
Gtk-Message: 12:24:29.091: Failed to load module "appmenu-gtk-module"
grep: /home/kronos/snap/fusion360/common/.wine/*.reg: No such file or directory
Gtk-Message: 12:24:29.202: Failed to load module "appmenu-gtk-module"
grep: /home/kronos/snap/fusion360/common/.wine/*.reg: No such file or directory
Gtk-Message: 12:24:29.309: Failed to load module "appmenu-gtk-module"
grep: /home/kronos/snap/fusion360/common/.wine/*.reg: No such file or directory
Gtk-Message: 12:24:29.417: Failed to load module "appmenu-gtk-module"
grep: /home/kronos/snap/fusion360/common/.wine/*.reg: No such file or directory
Gtk-Message: 12:24:29.526: Failed to load module "appmenu-gtk-module"
grep: /home/kronos/snap/fusion360/common/.wine/*.reg: No such file or directory
Gtk-Message: 12:24:29.640: Failed to load module "appmenu-gtk-module"
shm_unlink: No such file or directory
shm_open: Permission denied
ftruncate: Bad file descriptor
esync: up and running.
removed '/tmp/Fusion%20360%20Admin%20Install.exe'
/snap/fusion360/10/bin/sommelier: line 102: 27107 Broken pipe             yes
     27108 Terminated              | yad --progress --title="Installing ${EXE_NAME}" --progress-text= --width=400 --center --no-buttons --auto-close --auto-kill --on-top --pulsate
Running hook '/snap/fusion360/10/sommelier/hooks/post-install'
updated RUN_EXE=
Starting application..
```

**Comment by Thermionix** [comment]
This is related to the 'strict' confinement, on my machine I'd been running on devmode which wasn't restricting the interfaces - just testing which of the [interfaces are required](https://snapcraft.io/docs/supported-interfaces) and a new version will be up

**Comment by kz6fittycent** [comment]
> This is related to the 'strict' confinement, on my machine I'd been running on devmode which wasn't restricting the interfaces - just testing which of the [interfaces are required](https://snapcraft.io/docs/supported-interfaces) and a new version will be up

You may want to provide some instructions (for the time being) that include running in `devmode`. 

`sudo snap install --devmode fusion360`

**Comment by kz6fittycent** [comment]
Okay, running in `devmode` did the trick.

**Comment by Thermionix** [comment]
> > This is related to the 'strict' confinement, on my machine I'd been running on devmode which wasn't restricting the interfaces - just testing which of the [interfaces are required](https://snapcraft.io/docs/supported-interfaces) and a new version will be up
> 
> You may want to provide some instructions (for the time being) that include running in `devmode`.
> 
> `sudo snap install --devmode fusion360`

If I can't sort out the required interfaces in a day or so, I'll change confinement to devmode and it'll only be available as beta

**Comment by kz6fittycent** [comment]
> > > This is related to the 'strict' confinement, on my machine I'd been running on devmode which wasn't restricting the interfaces - just testing which of the [interfaces are required](https://snapcraft.io/docs/supported-interfaces) and a new version will be up
> > 
> > 
> > You may want to provide some instructions (for the time being) that include running in `devmode`.
> > `sudo snap install --devmode fusion360`
> 
> If I can't sort out the required interfaces in a day or so, I'll change confinement to devmode and it'll only be available as beta

Have you opened a thread on the [forum](https://forum.snapcraft.io/)?

**Comment by Thermionix** [comment]
I've moved it to beta for now

`sudo snap install --beta fusion360 --devmode`

**Comment by Rohan-Bansal** [comment]
![Screenshot from 2021-08-13 17-35-29](https://user-images.githubusercontent.com/36248672/129429245-916c6ebf-1f18-4401-b369-d6bbb64a1a03.png)

This seems to be the universal problem I'm having. That picture in the workspace is my wallpaper, and it seems the graphics are glitching and preventing anything from being displayed in the editor. I can open folders, toggle dropdowns, and even open files without a problem but nothing is displayed in the center besides a glitched screenshot.

**Comment by kz6fittycent** [comment]
> ![Screenshot from 2021-08-13 17-35-29](https://user-images.githubusercontent.com/36248672/129429245-916c6ebf-1f18-4401-b369-d6bbb64a1a03.png)
> 
> This seems to be the universal problem I'm having. That picture in the workspace is my wallpaper, and it seems the graphics are glitching and preventing anything from being displayed in the editor. I can open folders, toggle dropdowns, and even open files without a problem but nothing is displayed in the center besides a glitched screenshot.

You may want to open a separate issue. It'll make it much easier for @Thermionix to trouble-shoot and keep things orderly.

**Comment by kz6fittycent** [comment]
@Thermionix feel free to close this issue since it's launching. IMO the other issues listed may not be related.
