### ISSUE TITLE
Error launching streamed application

### ISSUE THREAD

**Issue by Richard-Haes-Ellis** [Thermionix/fusion360#10]
I'm getting the following error message after I tried to reinstall fusion 360. It previously worked fine but I had models that where edited on a newer build of fusion so I tried to reinstall it to get the latest version as there is no way to update it. Now it won't even install. 

![Screenshot from 2022-06-18 20-04-24](https://user-images.githubusercontent.com/42958218/174451083-dcf4c0f2-90ab-4631-ae74-667f3114585a.png)

Any idea on how to fix this issue?

**Comment by DragonflyRobotics** [comment]
I am also having a similar issue. I ran `sudo snap install --beta fusion360 --devmode` on my Zorin Pro(based on Ubuntu 20.04) with ZSH and then simply ran the application. It gave me the exact same error message. I also tried reinstalling it with no luck.

![image](https://user-images.githubusercontent.com/85193239/174490001-e8ea934f-9334-4566-ad17-9bbbb3eda1a2.png)

**Comment by Thermionix** [comment]
please try v0.8

**Comment by DragonflyRobotics** [comment]
Sorry, what do you mean v0.8? Is it a GitHub Release or a release on Snap?

**Comment by Richard-Haes-Ellis** [comment]
On snap, just uninstall fusion360 snap and reinstall as per the readme. Worked for me.

**Comment by DragonflyRobotics** [comment]
I will try that, thank you!
