### ISSUE TITLE
Install Plugins from AppStore

### ISSUE THREAD

**Issue by andreasseiler** [Thermionix/fusion360#20]
Did anyone manage to use the AppStore to install Plugins? If yes it would be helpful to know how. If I click on Fusion 360 App Store nothing happens. And I am not sure how to install the msi file downloaded via the browser ... Thanks in advance

**Comment by andreasseiler** [comment]
Figured it out ... The windows filesystem seems to be located under /home/myusername/snap/fusion360/common/.wine/drive_c

The Download folder for example is linked to the "Windows" Filesystem, so basically you can download the MSI from the Autodesk App Store and then execute it like so: fusion360.wine "C:/users/myusername/Downloads/GFGearGenerator_win64.msi"

Probably totally clear for most users, but wasn't for me ;)

**Comment by nobodyguy** [comment]
Thank you for documenting the solution :)
