### ISSUE TITLE
Sign in not working

### ISSUE THREAD

**Issue by botikori** [Thermionix/fusion360#21]
![Screenshot from 2023-04-08 20-51-38](https://user-images.githubusercontent.com/54451878/230738109-1469fde1-40c1-4822-a562-0f19c435adc3.png)
![Screenshot from 2023-04-08 20-53-14](https://user-images.githubusercontent.com/54451878/230738175-c6f970b9-b681-41d7-92eb-de39f7fcc3f8.png)
I assume the web browser should start in order to sign in, but nothing is happening. Because of this, I can't surpass the sign-in screen, which makes Fusion 360 unusable.

**Comment by lancepuk** [comment]
same problem with me

**Comment by zap117** [comment]
same here, both snap version and bottles

**Comment by MikhailovArtyom** [comment]
same problem with me

**Comment by zap117** [comment]
tried that but getting stuck on 'ShellExecuteEx' after chrome install

**Comment by pellle87** [comment]
I also cant get past login screen.

**Comment by dardardario** [comment]
Same issue here

**Comment by Matt2D3** [comment]
o0Ghost0o can you make a pull request with your fix

**Comment by skonakov** [comment]
Same for me

**Comment by manushawijekoon** [comment]
same issue here. Tried the workaround suggested here but still no luck. 
https://pullanswer.com/questions/welcome-screen-browser-login-not-opening

Also installed fusion360 using [usebottles](https://usebottles.com), still the same issue.

**Comment by Matt2D3** [comment]
I tried copying the cached login information from one instance of fusion360 (windows 10 VM) to ubuntu with no success. c:/users/AppData/Local/Autodesk/Autodesk Fusion 360/##random string of capital letters and numbers##. I will try copying other files related to the login later

**Comment by maxpolzin** [comment]
I encounter the same issue. It seems to be present since Fusion switched to SSO (which requires opening a browser).

**Comment by jonboy86** [comment]
same issue here fresh install

**Comment by DimitriBolt** [comment]
@o0Ghost0o 
> 4. run `WINEPREFIX=/home/ghostkiller/snap/fusion360 setup_dxvk.sh install`

In the folder `dxvk-2.2/` there is no file setup_dxvk.sh. There are only 2 folders
```
total 8
4932077 4 drwxr-xr-x 2 dimitri dimitri 4096 May 12 03:27 x32
4932078 4 drwxr-xr-x 2 dimitri dimitri 4096 May 12 03:27 x64
```

**Comment by o0Ghost0o** [comment]
@DimitriBolt You must download the 2.0 version

> 1. Download vulkan drivers from **(the 2.0 version as it includes the setup script)** https://github.com/doitsujin/dxvk/releases

so You will have the **dxvk-2.0** folder

**Comment by hanschanhs** [comment]
I believe a fix was found for this issue: https://github.com/cryinkfly/Autodesk-Fusion-360-for-Linux/issues/319

scroll to final comments

**Comment by o0Ghost0o** [comment]
I'll try it out

**Comment by markcm2** [comment]
Has a solution been found for this inability to login? I am new to this, first time install of popOS and just installed but get stuck at this same "web browser will open...login"

**Comment by manushawijekoon** [comment]
Disabling the SDK worked for me. Please check for comments.

**Comment by markcm2** [comment]
> Disabling the SDK worked for me. Please check for comments.

Thanks for the replay although I do not know what "the SDK" is, and I don't understand the statement "check for comments". I searched this thread for other comments about "SDK" in case that is what you are referencing although I do not see any.

Can you elaborate on what your fix was, and frame it for a Windows user who's new to popOS?

**Comment by manushawijekoon** [comment]
It's in a linked issue. Please check this:
https://github.com/cryinkfly/Autodesk-Fusion-360-for-Linux/issues/319#issuecomment-1569976242

**Comment by Smartich0ke** [comment]
I'm also having this problem. The current workaround I'm using for now is as referenced above. 

Running the snap with the following environment variable:
```
FUSION_IDSDK=false fusion360
```

**Comment by terrystech** [comment]
From Terminal type the following:

fusion_idsdk=false snap run fusion360

Fusion360 will launch with the old sign in.

**Comment by daniel-roulin** [comment]
To add to the previous comments, if you don't want to this every time you launch fusion 360, you can edit the .desktop file. 
Personally, I found it in `/var/lib/snapd/desktop/applications/fusion360_fusion360.desktop`. However, you need root privileges in order to edit it. You can do so by running:

`sudo nano /var/lib/snapd/desktop/applications/fusion360_fusion360.desktop`

Then, I edited this the Exec line. I replaced

`Exec=env BAMF_DESKTOP_FILE_HINT=/var/lib/snapd/desktop/applications/fusion360_fusion360.desktop /snap/bin/fusion360`

by

`Exec=env fusion_idsdk=false BAMF_DESKTOP_FILE_HINT=/var/lib/snapd/desktop/applications/fusion360_fusion360.desktop /snap/bin/fusion360`

Things worked immediately after, I didn't even need to logout or reboot.

**Comment by TNWT** [comment]
since it is not working for me, i want to uninstall is can you tell me how to uninstall it

**Comment by Smartich0ke** [comment]
> since it is not working for me, i want to uninstall is can you tell me how to uninstall it

`sudo snap remove fusion360`

**Comment by Misstborn** [comment]
This workaround isn't working as of right now, I'm running Manjaro kde and still getting an error when I try to launch the signin.

**Comment by Tobias-Auer** [comment]
same for me. Is there a new solution to it yet?
