### ISSUE TITLE
Bug: Ubuntu 22 First time bootup Error Code 0x80040c01

### ISSUE THREAD

**Issue by Ryanf55** [Thermionix/fusion360#24]
# Platform

* Ubuntu 22.04.3
* Installation method : `snap`
* Run method: `$ fusion360`

# Logs/Screenshot

![image](https://github.com/Thermionix/fusion360/assets/25047695/30220027-7ce8-4dc9-8459-099f3f25b8d5)

# Further info

This was the first time I tried Fusion360 on Linux. The first time I ran it, the application was installing all the applications. There were a few errors during the script, then this popped up.

**Comment by Dobarekk** [comment]
Same Problem here.

**Comment by CharlesXu1124** [comment]
same here, did you find a solution?

**Comment by 7HE-W0R1D** [comment]
same here, and I cannot trigger the browser for login. Not sure if these are related or not

**Comment by james-yoo** [comment]
Same here

**Comment by Dobarekk** [comment]
I actually solved it somehow, but I'm not sure anymore where I found the answer.
I'll look into it later.

**Comment by MikeJansen** [comment]
Same problem, Ubuntu 22.04.4.

**Comment by Dobarekk** [comment]
Yeah, I just wanted to look into it and I'm getting a new login error.
I'll revert back to dual booting with windows, as there's a few more things that I can't get to work on ubuntu.
So I won't be able to help y'all, sorry

**Comment by Thermionix** [comment]
fusion360 installer currently failing due to https://github.com/cryinkfly/Autodesk-Fusion-360-for-Linux/issues/408, I've pushed a [merge request to winehq](https://gitlab.winehq.org/wine/wine/-/merge_requests/5525)
