### ISSUE TITLE
Editor area graphics glitch

### ISSUE THREAD

**Issue by Rohan-Bansal** [Thermionix/fusion360#3]
![Screenshot from 2021-08-13 17-35-29](https://user-images.githubusercontent.com/36248672/129429245-916c6ebf-1f18-4401-b369-d6bbb64a1a03.png)

This seems to be the universal problem I'm having. That picture in the workspace is my wallpaper, and it seems the graphics are glitching and preventing anything from being displayed in the editor.

 I **can** open folders, toggle dropdowns, and even open files without a problem but nothing is displayed in the center besides a glitched screenshot.

**Comment by Thermionix** [comment]
I'd say this is related to wine opengl and graphics drivers

Can I get the following info;
Operating system (Fedora 34, ...)
Desktop environment (XFCE 4.16, ...)
Graphics card model
Graphics card driver (Version number)

**Comment by Rohan-Bansal** [comment]
Sure, here you go @Thermionix 

Operating system: Pop! OS 20.04
DE: GNOME 3.36.8 
Graphics card: Nvidia RTX 2060 Mobile
Graphics card driver: 465.31

**Comment by Thermionix** [comment]
Can you provide the output of `dpkg -l | awk '{print $2}' | grep nvidia`

**Comment by Thermionix** [comment]
I think you probably need `sudo apt-get install libnvidia-gl-465:i386`

**Comment by Rohan-Bansal** [comment]
output of `dpkg -l | awk '{print $2}' | grep nvidia`

```bash
libnvidia-cfg1-470:amd64
libnvidia-common-470
libnvidia-compute-460:amd64
libnvidia-compute-465:amd64
libnvidia-compute-470:amd64
libnvidia-compute-470:i386
libnvidia-decode-470:amd64
libnvidia-decode-470:i386
libnvidia-encode-470:amd64
libnvidia-encode-470:i386
libnvidia-extra-470:amd64
libnvidia-fbc1-470:amd64
libnvidia-fbc1-470:i386
libnvidia-gl-465:i386
libnvidia-gl-470:amd64
libnvidia-gl-470:i386
libnvidia-ifr1-470:amd64
libnvidia-ifr1-470:i386
nvidia-compute-utils-465
nvidia-compute-utils-470
nvidia-dkms-470
nvidia-driver-465
nvidia-driver-470
nvidia-kernel-common-470
nvidia-kernel-source-470
nvidia-settings
nvidia-utils-470
xserver-xorg-video-nvidia-470
```
I actually did what you suggested, also ran it from the command line and set my dedicated GPU flags manually and the bug disappeared.

However, now fusion 360 seems to have encountered another error. I'll open another issue.
