### ISSUE TITLE
Error when trying to run Fusion360

### ISSUE THREAD

**Issue by dylanlinux** [Thermionix/fusion360#5]
I installed the snap and ran Fusion360. It installed a few things and there was a big download, but then it stops with an error.
Here is the error:
![image](https://user-images.githubusercontent.com/50091049/144112366-6465ce58-5189-49c9-b3ac-0dc38b816349.png)

And here's what it's trying to do when the error comes up:
![image](https://user-images.githubusercontent.com/50091049/144112433-2e125fd5-439c-411e-a301-a8901e95e3c8.png)

Here's my system info:
![image](https://user-images.githubusercontent.com/50091049/144112508-045b3513-12e8-40c7-b51f-36e7bdf957dc.png)

**Comment by Thermionix** [comment]
please try v0.8
