### ISSUE TITLE
How to update Fusion

### ISSUE THREAD

**Issue by vooteleaer** [Thermionix/fusion360#7]
I noticed Fusion doesn't update itsself inside snap.
This is already becoming a problem as some designs madewith newer version of Fusion require update...

**Comment by Thermionix** [comment]
`fusion360.wine "C:\Program Files\Autodesk\webdeploy\meta\streamer\20220519164134\streamer.exe" --globalinstall --process update --quiet`
you can check the log file with
`fusion360.wine "C:\users\$USER\AppData\Local\Autodesk\autodesk.webdeploy.streamer.log"`
