### ISSUE TITLE
Installation failed Snap on fedora 36

### ISSUE THREAD

**Issue by oufmilo** [Thermionix/fusion360#9]
Hello,

I tried to install fusion360 on my laptop which is running the latest version of Fedora 36.

I have this error message as attached on the screen.

![Capture d’écran du 2022-05-19 18-18-40](https://user-images.githubusercontent.com/44617467/170242011-5513af21-6bea-46fb-a2d5-03797612767f.png)

Before it was running fine with Fedora35, I tried to reinstall Fusion360 without success.

Any suggestions ?

Thanks.

**Comment by oufmilo** [comment]
UP ??

**Comment by Diazblo** [comment]
The new Fusion 360 installer has additional requirements. You could try this repository instead [cryinkfly/Autodesk-Fusion-360-for-Linux](https://github.com/cryinkfly/Autodesk-Fusion-360-for-Linux)

**Comment by Thermionix** [comment]
please try v0.8
